version: '3.8'

services:
  account-manager:
    image: docker.pkg.github.com/ledgerhq/lama/lama-account-manager:${ACCOUNT_MANAGER_VERSION}
    environment:
      ACCOUNT_MANAGER_PORT: ${ACCOUNT_MANAGER_PORT}
      ACCOUNT_MANAGER_JDBC_URL: ${ACCOUNT_MANAGER_JDBC_URL}
      ACCOUNT_MANAGER_POSTGRES_USER: ${ACCOUNT_MANAGER_POSTGRES_USER}
      ACCOUNT_MANAGER_POSTGRES_PASSWORD: ${ACCOUNT_MANAGER_POSTGRES_PASSWORD}
      WORKER_EVENTS_EXCHANGE_NAME: ${WORKER_EVENTS_EXCHANGE_NAME}
      LAMA_EVENTS_EXCHANGE_NAME: ${LAMA_EVENTS_EXCHANGE_NAME}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_VIRTUAL_HOST: ${RABBIT_VIRTUAL_HOST}
      RABBIT_CONNECTION_TIMEOUT: ${RABBIT_CONNECTION_TIMEOUT}
      RABBIT_SSL: ${RABBIT_SSL}
      RABBIT_USERNAME: ${RABBIT_USERNAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      BITCOIN_SYNC_FREQUENCY: ${BITCOIN_SYNC_FREQUENCY}
    ports:
      - "${ACCOUNT_MANAGER_PORT}:${ACCOUNT_MANAGER_PORT}"
    depends_on:
      - postgres
      - rabbitmq
      - redis
      - flyway-account-manager

  service:
    image: docker.pkg.github.com/ledgerhq/lama/lama-service:${SERVICE_VERSION}
    environment:
      SERVICE_HOST: ${SERVICE_HOST}
      SERVICE_PORT: ${SERVICE_PORT}
      ACCOUNT_MANAGER_HOST: ${ACCOUNT_MANAGER_HOST}
      ACCOUNT_MANAGER_PORT: ${ACCOUNT_MANAGER_PORT}
      ACCOUNT_MANAGER_SSL: ${ACCOUNT_MANAGER_SSL}
      BITCOIN_KEYCHAIN_HOST: ${BITCOIN_KEYCHAIN_HOST}
      BITCOIN_KEYCHAIN_PORT: ${BITCOIN_KEYCHAIN_PORT}
      BITCOIN_KEYCHAIN_SSL: ${BITCOIN_KEYCHAIN_SSL}
      BITCOIN_INTERPRETER_HOST: ${BITCOIN_INTERPRETER_HOST}
      BITCOIN_INTERPRETER_PORT: ${BITCOIN_INTERPRETER_PORT}
      BITCOIN_INTERPRETER_SSL: ${BITCOIN_INTERPRETER_SSL}
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    depends_on:
      - account-manager
      - bitcoin-keychain-svc
      - bitcoin-interpreter

  postgres:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "./tooling/postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 15s
      retries: 10

  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "6379:6379"

  flyway-account-manager:
    image: flyway/flyway:${FLYWAY_VERSION}
    command: -url=${ACCOUNT_MANAGER_JDBC_URL} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate
    volumes:
      - "./account-manager/src/main/resources/db/migration:/flyway/sql"
    depends_on:
      - postgres

  flyway-bitcoin-interpreter:
    image: flyway/flyway:${FLYWAY_VERSION}
    command: -url=${BITCOIN_INTERPRETER_JDBC_URL} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate
    volumes:
      - "./coins/bitcoin/interpreter/src/main/resources/db/migration:/flyway/sql"
    depends_on:
      - postgres

  bitcoin-svc:
    image: ledgerhq/bitcoin-svc:${BITCOIN_SVC_VERSION}
    environment:
      BITCOIN_HOST: ${BITCOIN_SVC_HOST}
      BITCOIN_PORT: ${BITCOIN_SVC_PORT}
    ports:
      - ${BITCOIN_SVC_PORT}:${BITCOIN_SVC_PORT}

  bitcoin-keychain-svc:
    image: ledgerhq/bitcoin-keychain-svc:${BITCOIN_KEYCHAIN_VERSION}
    environment:
      BITCOIN_KEYCHAIN_HOST: ${BITCOIN_KEYCHAIN_HOST}
      BITCOIN_KEYCHAIN_PORT: ${BITCOIN_KEYCHAIN_PORT}
      BITCOIN_HOST: ${BITCOIN_SVC_HOST}
      BITCOIN_PORT: ${BITCOIN_SVC_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: 1
    depends_on:
      - bitcoin-svc
    ports:
      - ${BITCOIN_KEYCHAIN_PORT}:${BITCOIN_KEYCHAIN_PORT}

  bitcoin-interpreter:
    image: docker.pkg.github.com/ledgerhq/lama/lama-bitcoin-interpreter:${BITCOIN_INTERPRETER_VERSION}
    environment:
      BITCOIN_INTERPRETER_JDBC_URL: ${BITCOIN_INTERPRETER_JDBC_URL}
      BITCOIN_INTERPRETER_POSTGRES_USER: ${BITCOIN_INTERPRETER_POSTGRES_USER}
      BITCOIN_INTERPRETER_POSTGRES_PASSWORD: ${BITCOIN_INTERPRETER_POSTGRES_PASSWORD}
      BITCOIN_INTERPRETER_PORT: ${BITCOIN_INTERPRETER_PORT}
    depends_on:
      - postgres
      - flyway-bitcoin-interpreter
    ports:
      - ${BITCOIN_INTERPRETER_PORT}:${BITCOIN_INTERPRETER_PORT}

  bitcoin-worker:
    image: docker.pkg.github.com/ledgerhq/lama/lama-bitcoin-worker:${BITCOIN_WORKER_VERSION}
    environment:
      WORKER_EVENTS_EXCHANGE_NAME: ${WORKER_EVENTS_EXCHANGE_NAME}
      LAMA_EVENTS_EXCHANGE_NAME: ${LAMA_EVENTS_EXCHANGE_NAME}
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_VIRTUAL_HOST: ${RABBIT_VIRTUAL_HOST}
      RABBIT_CONNECTION_TIMEOUT: ${RABBIT_CONNECTION_TIMEOUT}
      RABBIT_SSL: ${RABBIT_SSL}
      RABBIT_USERNAME: ${RABBIT_USERNAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      BITCOIN_KEYCHAIN_HOST: ${BITCOIN_KEYCHAIN_HOST}
      BITCOIN_KEYCHAIN_PORT: ${BITCOIN_KEYCHAIN_PORT}
      BITCOIN_KEYCHAIN_SSL: ${BITCOIN_KEYCHAIN_SSL}
      BITCOIN_EXPLORER_URI: ${BITCOIN_EXPLORER_URI}
      BITCOIN_EXPLORER_ADDRESSES_SIZE: ${BITCOIN_EXPLORER_ADDRESSES_SIZE}
      BITCOIN_EXPLORER_TXS_BATCH_SIZE: ${BITCOIN_EXPLORER_TXS_BATCH_SIZE}
      BITCOIN_EXPLORER_TIMEOUT: ${BITCOIN_EXPLORER_TIMEOUT}
      BITCOIN_INTERPRETER_HOST: ${BITCOIN_INTERPRETER_HOST}
      BITCOIN_INTERPRETER_PORT: ${BITCOIN_INTERPRETER_PORT}
      BITCOIN_INTERPRETER_SSL: ${BITCOIN_INTERPRETER_SSL}
    depends_on:
      - rabbitmq
      - bitcoin-keychain-svc
      - bitcoin-interpreter
