# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2.1

orbs:
  docker: ledger/docker@volatile
  codecov: codecov/codecov@1.0.2

aliases:
  - &filter_all_tags
    tags:
      only: /.*/
  - &restore_docker_cache
    keys:
      - lama-cache-docker-{{ .Branch }}-{{ checksum "build.sbt" }}
      - lama-cache-docker-{{ .Branch }}
      - lama-cache-docker
  - &save_docker_cache
    key: lama-cache-docker-{{ .Branch }}-{{ checksum "build.sbt" }}
    paths:
      - ~/.ivy2
      - ~/.sbt

commands:
  initlama:
    description: "Checkout lama project with submodules and restore docker cache"
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update
      - restore_cache: *restore_docker_cache

parameters:
  sbt:
    type: string
    default: SBT_OPTS="-Xss512m" sbt -Dsbt.ivy.home=.ivy2 -sbt-dir .sbt

jobs:
  compile:
    docker:
      - image: circleci/openjdk:14.0.2-jdk-buster
        environment:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - initlama
      - run:
          name: Compile
          command: << pipeline.parameters.sbt >> compile test:compile it:compile
      - save_cache: *save_docker_cache

  scala_linter:
    docker:
      - image: circleci/openjdk:14.0.2-jdk-buster
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - initlama
      - run:
          name: Run scalastyle
          command: << pipeline.parameters.sbt >> scalastyle

  unit_tests:
    docker:
      - image: circleci/openjdk:14.0.2-jdk-buster
        environment:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
    steps:
      - initlama
      - run:
          name: Run Common unit tests
          command: << pipeline.parameters.sbt >> common/test
      - run:
          name: Run Account Manager unit tests
          command: << pipeline.parameters.sbt >> accountManager/test
      - run:
          name: Run Bitcoin Service unit tests
          command: << pipeline.parameters.sbt >> btcService/test
      - run:
          name: Run Bitcoin Worker unit tests
          command: << pipeline.parameters.sbt >> btcWorker/test
      - run:
          name: Run Bitcoin Interpreter unit tests
          command: << pipeline.parameters.sbt >> btcInterpreter/test
  package:
    docker:
      - image: circleci/openjdk:14.0.2-jdk-buster
        environment:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
    steps:
      - initlama
      - run:
          name: Package Jar
          command: << pipeline.parameters.sbt >> assembly

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - compile
      - unit_tests:
          requires:
            - compile
      # FIXME: enable linter compliance
      #     - scala_linter:
      #          requires:
      #            - compile
      - docker/build_image:
          context: githubpkg
          docker_build_target: account-manager
          requires:
            - compile
          after_checkout:
            - run:
                name: Assembly
                command: |
                  git submodule init
                  git submodule update
                  << pipeline.parameters.sbt >> assembly
      - docker/publish_image:
          context: githubpkg
          requires:
            - docker/build_image
            - unit_tests
# FIXME:    - scala_linter
