# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2.1

jobs:
  just_pass_please:
    docker:
      - image: circleci/openjdk:14.0.2-jdk-buster
    steps:
      - run: echo 'k deal'

workflows:
  pass:
    jobs:
      - just_pass_please